travis:
  secure:
    BINSTAR_TOKEN: spPIWe90YOmsO1afhbk5hbz08gpzY9QGeILHJ+nZQbqq9jjhTEmatykTafNWu13XcZGj4DPnpCJln198dIkGUzL/nDtAV44A1sLxjLtxjNQ4NruS0oLueEANXqFBxF06IiY6ovq3IrgeAfRJS5pq+sHDLgKh5t/egKA9zQly3XFa4Sr2stDlBM+phqJSkTrr4glfESx4ZS6PiVOpX22n6bX4ocUoYs8lOgKVATq/MS7BHS5YdkhNp+3cRIDeSq3lOB5ffpF/QZ4uzQFYMgswoqa/ILtehGByfKEJJlyJdz763DOQzo9HypOSKpBFrc9LCMVK6IlWe2qmDrR6B4S/s6t57tBrwn6Vj15u5xUof0XTeFHdYWUwV5fmSpdK681JTRAqdYNpfiBunVSye5tCGozIBC7hJCpU6CSPpbIezhruSdPFgL62d7/k8xKkdNyJlGZTn1wn9+bHelJwt/t2TZ6SMnPPPqD3BmESNLuNQNZLBg7KijUJKn0xn9I9LU3BGPGAftbaS0Je4Rd5WEDHqBOeEjiZEjtA7Njb35mRmH2U7Jz3FH6JBqKZDic4x9uJHfbxJw72o+ZOdqhKVvd43dTQraLNUMIm5Hae0TRpFt/m2UKb6pD3Vk1KT2CXmk4CYr4nVWRG1+m+0b057ugMbbFs26rvOgT/Pugw/XHoCpQ=
conda_forge_output_validation: true
bot:
  automerge: true
